# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/yangjeep/playground_c_search

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/yangjeep/playground_c_search

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\" \"library\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yangjeep/playground_c_search/CMakeFiles /home/yangjeep/playground_c_search//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yangjeep/playground_c_search/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named common

# Build rule for target.
common: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 common
.PHONY : common

# fast build rule for target.
common/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/build
.PHONY : common/fast

#=============================================================================
# Target rules for targets named test_gtrie

# Build rule for target.
test_gtrie: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_gtrie
.PHONY : test_gtrie

# fast build rule for target.
test_gtrie/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_gtrie.dir/build.make CMakeFiles/test_gtrie.dir/build
.PHONY : test_gtrie/fast

#=============================================================================
# Target rules for targets named test_gtrie_io

# Build rule for target.
test_gtrie_io: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_gtrie_io
.PHONY : test_gtrie_io

# fast build rule for target.
test_gtrie_io/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_gtrie_io.dir/build.make CMakeFiles/test_gtrie_io.dir/build
.PHONY : test_gtrie_io/fast

#=============================================================================
# Target rules for targets named test_index_writer

# Build rule for target.
test_index_writer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_index_writer
.PHONY : test_index_writer

# fast build rule for target.
test_index_writer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_index_writer.dir/build.make CMakeFiles/test_index_writer.dir/build
.PHONY : test_index_writer/fast

#=============================================================================
# Target rules for targets named test_indexer

# Build rule for target.
test_indexer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_indexer
.PHONY : test_indexer

# fast build rule for target.
test_indexer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_indexer.dir/build.make CMakeFiles/test_indexer.dir/build
.PHONY : test_indexer/fast

#=============================================================================
# Target rules for targets named index_writer

# Build rule for target.
index_writer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 index_writer
.PHONY : index_writer

# fast build rule for target.
index_writer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/index_writer.dir/build.make CMakeFiles/index_writer.dir/build
.PHONY : index_writer/fast

#=============================================================================
# Target rules for targets named unity

# Build rule for target.
unity: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unity
.PHONY : unity

# fast build rule for target.
unity/fast:
	$(MAKE) $(MAKESILENT) -f _deps/unity-build/CMakeFiles/unity.dir/build.make _deps/unity-build/CMakeFiles/unity.dir/build
.PHONY : unity/fast

src/common/gtrie.o: src/common/gtrie.c.o
.PHONY : src/common/gtrie.o

# target to build an object file
src/common/gtrie.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/common/gtrie.c.o
.PHONY : src/common/gtrie.c.o

src/common/gtrie.i: src/common/gtrie.c.i
.PHONY : src/common/gtrie.i

# target to preprocess a source file
src/common/gtrie.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/common/gtrie.c.i
.PHONY : src/common/gtrie.c.i

src/common/gtrie.s: src/common/gtrie.c.s
.PHONY : src/common/gtrie.s

# target to generate assembly for a file
src/common/gtrie.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/common/gtrie.c.s
.PHONY : src/common/gtrie.c.s

src/common/gtrie_io.o: src/common/gtrie_io.c.o
.PHONY : src/common/gtrie_io.o

# target to build an object file
src/common/gtrie_io.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/common/gtrie_io.c.o
.PHONY : src/common/gtrie_io.c.o

src/common/gtrie_io.i: src/common/gtrie_io.c.i
.PHONY : src/common/gtrie_io.i

# target to preprocess a source file
src/common/gtrie_io.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/common/gtrie_io.c.i
.PHONY : src/common/gtrie_io.c.i

src/common/gtrie_io.s: src/common/gtrie_io.c.s
.PHONY : src/common/gtrie_io.s

# target to generate assembly for a file
src/common/gtrie_io.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/common/gtrie_io.c.s
.PHONY : src/common/gtrie_io.c.s

src/common/index_writer.o: src/common/index_writer.c.o
.PHONY : src/common/index_writer.o

# target to build an object file
src/common/index_writer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/common/index_writer.c.o
.PHONY : src/common/index_writer.c.o

src/common/index_writer.i: src/common/index_writer.c.i
.PHONY : src/common/index_writer.i

# target to preprocess a source file
src/common/index_writer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/common/index_writer.c.i
.PHONY : src/common/index_writer.c.i

src/common/index_writer.s: src/common/index_writer.c.s
.PHONY : src/common/index_writer.s

# target to generate assembly for a file
src/common/index_writer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/common/index_writer.c.s
.PHONY : src/common/index_writer.c.s

src/common/indexer.o: src/common/indexer.c.o
.PHONY : src/common/indexer.o

# target to build an object file
src/common/indexer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/common/indexer.c.o
.PHONY : src/common/indexer.c.o

src/common/indexer.i: src/common/indexer.c.i
.PHONY : src/common/indexer.i

# target to preprocess a source file
src/common/indexer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/common/indexer.c.i
.PHONY : src/common/indexer.c.i

src/common/indexer.s: src/common/indexer.c.s
.PHONY : src/common/indexer.s

# target to generate assembly for a file
src/common/indexer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/common/indexer.c.s
.PHONY : src/common/indexer.c.s

src/common/logging.o: src/common/logging.c.o
.PHONY : src/common/logging.o

# target to build an object file
src/common/logging.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/common/logging.c.o
.PHONY : src/common/logging.c.o

src/common/logging.i: src/common/logging.c.i
.PHONY : src/common/logging.i

# target to preprocess a source file
src/common/logging.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/common/logging.c.i
.PHONY : src/common/logging.c.i

src/common/logging.s: src/common/logging.c.s
.PHONY : src/common/logging.s

# target to generate assembly for a file
src/common/logging.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/common/logging.c.s
.PHONY : src/common/logging.c.s

src/index_writer/index_writer_main.o: src/index_writer/index_writer_main.c.o
.PHONY : src/index_writer/index_writer_main.o

# target to build an object file
src/index_writer/index_writer_main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/index_writer.dir/build.make CMakeFiles/index_writer.dir/src/index_writer/index_writer_main.c.o
.PHONY : src/index_writer/index_writer_main.c.o

src/index_writer/index_writer_main.i: src/index_writer/index_writer_main.c.i
.PHONY : src/index_writer/index_writer_main.i

# target to preprocess a source file
src/index_writer/index_writer_main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/index_writer.dir/build.make CMakeFiles/index_writer.dir/src/index_writer/index_writer_main.c.i
.PHONY : src/index_writer/index_writer_main.c.i

src/index_writer/index_writer_main.s: src/index_writer/index_writer_main.c.s
.PHONY : src/index_writer/index_writer_main.s

# target to generate assembly for a file
src/index_writer/index_writer_main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/index_writer.dir/build.make CMakeFiles/index_writer.dir/src/index_writer/index_writer_main.c.s
.PHONY : src/index_writer/index_writer_main.c.s

test/test_gtrie.o: test/test_gtrie.c.o
.PHONY : test/test_gtrie.o

# target to build an object file
test/test_gtrie.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_gtrie.dir/build.make CMakeFiles/test_gtrie.dir/test/test_gtrie.c.o
.PHONY : test/test_gtrie.c.o

test/test_gtrie.i: test/test_gtrie.c.i
.PHONY : test/test_gtrie.i

# target to preprocess a source file
test/test_gtrie.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_gtrie.dir/build.make CMakeFiles/test_gtrie.dir/test/test_gtrie.c.i
.PHONY : test/test_gtrie.c.i

test/test_gtrie.s: test/test_gtrie.c.s
.PHONY : test/test_gtrie.s

# target to generate assembly for a file
test/test_gtrie.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_gtrie.dir/build.make CMakeFiles/test_gtrie.dir/test/test_gtrie.c.s
.PHONY : test/test_gtrie.c.s

test/test_gtrie_io.o: test/test_gtrie_io.c.o
.PHONY : test/test_gtrie_io.o

# target to build an object file
test/test_gtrie_io.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_gtrie_io.dir/build.make CMakeFiles/test_gtrie_io.dir/test/test_gtrie_io.c.o
.PHONY : test/test_gtrie_io.c.o

test/test_gtrie_io.i: test/test_gtrie_io.c.i
.PHONY : test/test_gtrie_io.i

# target to preprocess a source file
test/test_gtrie_io.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_gtrie_io.dir/build.make CMakeFiles/test_gtrie_io.dir/test/test_gtrie_io.c.i
.PHONY : test/test_gtrie_io.c.i

test/test_gtrie_io.s: test/test_gtrie_io.c.s
.PHONY : test/test_gtrie_io.s

# target to generate assembly for a file
test/test_gtrie_io.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_gtrie_io.dir/build.make CMakeFiles/test_gtrie_io.dir/test/test_gtrie_io.c.s
.PHONY : test/test_gtrie_io.c.s

test/test_index_writer.o: test/test_index_writer.c.o
.PHONY : test/test_index_writer.o

# target to build an object file
test/test_index_writer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_index_writer.dir/build.make CMakeFiles/test_index_writer.dir/test/test_index_writer.c.o
.PHONY : test/test_index_writer.c.o

test/test_index_writer.i: test/test_index_writer.c.i
.PHONY : test/test_index_writer.i

# target to preprocess a source file
test/test_index_writer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_index_writer.dir/build.make CMakeFiles/test_index_writer.dir/test/test_index_writer.c.i
.PHONY : test/test_index_writer.c.i

test/test_index_writer.s: test/test_index_writer.c.s
.PHONY : test/test_index_writer.s

# target to generate assembly for a file
test/test_index_writer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_index_writer.dir/build.make CMakeFiles/test_index_writer.dir/test/test_index_writer.c.s
.PHONY : test/test_index_writer.c.s

test/test_indexer.o: test/test_indexer.c.o
.PHONY : test/test_indexer.o

# target to build an object file
test/test_indexer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_indexer.dir/build.make CMakeFiles/test_indexer.dir/test/test_indexer.c.o
.PHONY : test/test_indexer.c.o

test/test_indexer.i: test/test_indexer.c.i
.PHONY : test/test_indexer.i

# target to preprocess a source file
test/test_indexer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_indexer.dir/build.make CMakeFiles/test_indexer.dir/test/test_indexer.c.i
.PHONY : test/test_indexer.c.i

test/test_indexer.s: test/test_indexer.c.s
.PHONY : test/test_indexer.s

# target to generate assembly for a file
test/test_indexer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_indexer.dir/build.make CMakeFiles/test_indexer.dir/test/test_indexer.c.s
.PHONY : test/test_indexer.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... common"
	@echo "... index_writer"
	@echo "... test_gtrie"
	@echo "... test_gtrie_io"
	@echo "... test_index_writer"
	@echo "... test_indexer"
	@echo "... unity"
	@echo "... src/common/gtrie.o"
	@echo "... src/common/gtrie.i"
	@echo "... src/common/gtrie.s"
	@echo "... src/common/gtrie_io.o"
	@echo "... src/common/gtrie_io.i"
	@echo "... src/common/gtrie_io.s"
	@echo "... src/common/index_writer.o"
	@echo "... src/common/index_writer.i"
	@echo "... src/common/index_writer.s"
	@echo "... src/common/indexer.o"
	@echo "... src/common/indexer.i"
	@echo "... src/common/indexer.s"
	@echo "... src/common/logging.o"
	@echo "... src/common/logging.i"
	@echo "... src/common/logging.s"
	@echo "... src/index_writer/index_writer_main.o"
	@echo "... src/index_writer/index_writer_main.i"
	@echo "... src/index_writer/index_writer_main.s"
	@echo "... test/test_gtrie.o"
	@echo "... test/test_gtrie.i"
	@echo "... test/test_gtrie.s"
	@echo "... test/test_gtrie_io.o"
	@echo "... test/test_gtrie_io.i"
	@echo "... test/test_gtrie_io.s"
	@echo "... test/test_index_writer.o"
	@echo "... test/test_index_writer.i"
	@echo "... test/test_index_writer.s"
	@echo "... test/test_indexer.o"
	@echo "... test/test_indexer.i"
	@echo "... test/test_indexer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

